### ISSUE TITLE
User theme black font on black background

### ISSUE THREAD

**Issue by vlgrs** [Michedev/Ant-Dracula-Blue#4]
Ubuntu version 19.10
The color of the text on the status menu and application menu is too dark and non readable (except on mouseover when it became white), i try to hard fix it but didin't succeed.

https://imgur.com/U3DQxrE

**Comment by ramonguimaraes** [comment]
> Ubuntu version 19.10
> The color of the text on the status menu and application menu is too dark and non readable (except on mouseover when it became white), i try to hard fix it but didin't succeed.
> 
> https://imgur.com/U3DQxrE
HELLO :)
Add this code to the beginning of the gnome-shell.css file

```
* {
  color: white;
}
```

it was good here
Hug from Brazil

**Comment by vlgrs** [comment]
Thank you sir, i feel dumb ahah
